### ISSUE TITLE
tinyBert general model with `cased`

### ISSUE THREAD

**Issue by sv-github** [huawei-noah/Pretrained-Language-Model#31]
Hello,

Have you done general distillation using the `bert-base-cased` model?
and would you have the `General_TinyBERT_v2(4layer-312dim)` cased model available?

When trying `python3 task_distill.py --teacher_model $FT_BERT_BASE_DIR --student_model $GENERAL_TINYBERT_DIR ... ` on a Fine-Tuned model that is `'bert-cased'`,
a CUDA error is thrown

**Comment by itsucks** [comment]
Sorry, we haven't done general distillation with case model and there is no plans to  release cased general_TinyBERT, is there a reason that you need cased model?

Could you provide CUDA error message in detail?

**Comment by sv-github** [comment]
Alright, thanks for responding

I was interested in a cased general model because it appears that a fine-tuned cased model has better performance for my 4 class dataset

```
Iteration:   0%|                                                                   | 2/24029 [00:00<1:06:37,  6.01it/s]
Epoch:   0%|                                                                                     | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "task_distill.py", line 1148, in <module>
    main()
  File "task_distill.py", line 981, in main
    teacher_logits, teacher_atts, teacher_reps = teacher_model(input_ids, segment_ids, input_mask)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/svyat/Pretrained-Language-Model/TinyBERT/transformer/modeling.py", line 1133, in forward
    output_all_encoded_layers=True, output_att=True)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/svyat/Pretrained-Language-Model/TinyBERT/transformer/modeling.py", line 834, in forward
    extended_attention_mask)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/svyat/Pretrained-Language-Model/TinyBERT/transformer/modeling.py", line 515, in forward
    hidden_states, attention_mask)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/svyat/Pretrained-Language-Model/TinyBERT/transformer/modeling.py", line 498, in forward
    layer_output = self.output(intermediate_output, attention_output)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/svyat/Pretrained-Language-Model/TinyBERT/transformer/modeling.py", line 481, in forward
    hidden_states = self.dense(hidden_states)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/svyat/.local/share/virtualenvs/text_classifiers_transactions-t-TEOM59/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by nlpBeginner** [comment]
check your config.json file. 
the error suggests that your input("token_id") exceed the vocab_size.
